version: '3.3'

services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_DB=task_queue
    ports:
      - ${DB_PORT}:5432
    volumes:
      - data:/var/lib/postgresql

  rabbit:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
    - ${RABBITMQ_PORT}:5672

volumes:
  data:
    external:
      name: data
