"""initialize

Revision ID: 06bba5b273c7
Revises: 
Create Date: 2019-04-27 11:59:21.116343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06bba5b273c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('status', sa.Enum('in_queue', 'running', 'completed', name='taskstatusenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
