"""init_schema

Revision ID: bfc18deece4c
Revises: 
Create Date: 2019-04-27 22:24:42.014289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bfc18deece4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("create extension pgcrypto;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('status', sa.Enum('in_queue', 'running', 'completed', name='taskstatusenum'), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('execution_time', postgresql.INTERVAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###

    op.execute("drop extension pgcrypto;")
